[versions]
kotlin = "2.2.10"
axmlprinter = "v1.0.0"
apksig = "8.13.2"
json = "20240303"
ahocorasick = "0.6.3"
snakeyaml = "2.2"
kotlinxCli = "0.3.6"
junitJupiter = "5.10.2"
junitPlatform = "1.10.2"
protobuf = "4.32.0"
gson = "2.11.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
axmlprinter = { group = "com.github.rednaga", name = "axmlprinter", version.ref = "axmlprinter" }
apksig = { group = "com.android.tools.build", name = "apksig", version.ref = "apksig" }
org-json = { group = "org.json", name = "json", version.ref = "json" }
ahocorasick = { group = "org.ahocorasick", name = "ahocorasick", version.ref = "ahocorasick" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeyaml" }
kotlinx-cli = { group = "org.jetbrains.kotlinx", name = "kotlinx-cli", version.ref = "kotlinxCli" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatform" }
protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
